on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Default test
        run: echo "[PASS] Test ran successfully"
          
      - name: Run tests with Annotations
        run: |
            echo "::notice title=Test Passed::[PASS] Test ran successfully"
            echo "::warning title=Test Warning::[Warning] Test sends warning"
            echo "::error title=Test Failed::[FAIL] Test encountered an error"

      - name: Run tests with color
        run: |
          echo "Default"
          echo -e "\033[31m[FAIL] Test encountered an error\033[0m"  # Red color
          echo -e "\033[32m[PASS] Test ran successfully\033[0m"  # Green color
          echo -e "\033[33m[FAIL] Test color Yellow\033[0m"  # Yellow color
          echo -e "\033[34m[FAIL] Test color Blue\033[0m"  # Blue color
          echo -e "\033[35m[FAIL] Test color Magenta\033[0m"  # Magenta color
          echo -e "\033[36m[FAIL] Test color Cyan\033[0m"  # Cyan color
          echo -e "\033[37m[FAIL] Test color White\033[0m"  # White color
          echo "Bold Text"
          echo -e "\033[1;31m[FAIL] Test encountered an error\033[0m"  # Red color
          echo -e "\033[1;32m[PASS] Test ran successfully\033[0m"  # Green color
          echo -e "\033[1;33m[FAIL] Test color Yellow\033[0m"  # Yellow color
          echo "Background Color"
          echo -e "\033[41m[FAIL] Test encountered an error\033[0m"  # Red color
          echo -e "\033[42m[PASS] Test ran successfully\033[0m"  # Green color
          echo -e "\033[43m[FAIL] Test color Yellow\033[0m"  # Yellow color
          echo "High Intensity "
          echo -e "\033[91m[FAIL] Test encountered an error\033[0m"  # Red color
          echo -e "\033[92m[PASS] Test ran successfully\033[0m"  # Green color
          echo -e "\033[93m[FAIL] Test color Yellow\033[0m"  # Yellow color
          echo "High Intensity Background"
          echo -e "\033[101m[FAIL] Test encountered an error\033[0m"  # Red color
          echo -e "\033[102m[PASS] Test ran successfully\033[0m"  # Green color
          echo -e "\033[103m[FAIL] Test color Yellow\033[0m"  # Yellow color
          echo "Combined"
          echo -e "\033[42m[PASS]\033[0m\033[1;32m Test ran successfully\033[0m"  # Green color
          echo -e "\033[41m[FAIL]\033[0m\033[1;31m Test failed\033[0m"  # Red color
          echo -e "\033[43m[WARNING]\033[0m\033[1;33m Test send warning\033[0m"  # Yellow color


      - name: Run tests with emojis
        run: |
          echo "✅ [PASS] Test ran successfully"
          echo "❌ [FAIL] Test failed"

      - name: Run tests with grouping
        run: |
          echo "::group::Grouped Tests:"
          echo -e "\033[32m[PASS] Test1 ran successfully\033[0m"
          echo -e "\033[31m[FAIL] Test2 failed\033[0m"
          echo -e "\033[33m[Warning] Test3 sends warning\033[0m"
          echo "::endgroup::"
