on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          # Simulating a test condition
          echo "[PASS] Test ran successfully"

      - name: Annotate success
        run: |
          echo "::notice title=Test Passed::[PASS] Test ran successfully"  # Simulates green output

      - name: Annotate failure (example)
        if: ${{ failure() }}
        run: echo "::error title=Test Failed::[FAIL] Test encountered an error"

      - name: Run tests with color
        run: |
          echo -e "\033[32m[PASS] Test ran successfully\033[0m"  # Green color
          echo -e "\033[31m[FAIL] Test encountered an error\033[0m"  # Red color
