on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          # Simulating a test condition
          echo "[PASS] Test ran successfully"

      - name: Annotate success
        run: |
          echo "::notice title=Test Passed::[PASS] Test ran successfully"  # Simulates green output

      - name: Annotate failure (example)
        if: ${{ failure() }}
        run: echo "::error title=Test Failed::[FAIL] Test encountered an error"

      - name: Run tests with color
        run: |
          echo -e "\033[31m[PASS] Test encountered an error\033[0m"  # Red color
          echo -e "\033[32m[FAIL] Test ran successfully\033[0m"  # Green color
          echo -e "\033[33m[FAIL] Test color Yellow\033[0m"  # Yellow color
          echo -e "\033[34m[FAIL] Test color Blue\033[0m"  # Blue color
          echo -e "\033[35m[FAIL] Test color Magenta\033[0m"  # Magenta color
          echo -e "\033[36m[FAIL] Test color Cyan\033[0m"  # Cyan color
          echo -e "\033[37m[FAIL] Test color White\033[0m"  # White color

      - name: Run tests with emojis
        run: |
          echo "✅ [PASS] Test ran successfully"
          echo "❌ [FAIL] Test failed"

      - name: Run tests with grouping
        run: |
          echo "::group::Running tests"
          echo "[PASS] Test ran successfully"
          echo "::endgroup::"
