name: Workflow with Multiple Failure Summaries

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Init Summary
        run: |
          echo "### Workflow Summary" >> $GITHUB_STEP_SUMMARY
          echo "## Errors:" >> $GITHUB_STEP_SUMMARY

      - name: Step 1 - Run tests
        id: run_tests_1
        run: |
          echo "Running tests..."
          exit 1  # Simulate failure
        continue-on-error: true

      - name: Log Test Failure
        if: steps.run_tests_1.outcome == 'failure'
        run: |
          echo "- 'Step 1 - Run tests' failed." >> $GITHUB_STEP_SUMMARY

      - name: Step 2 - Run tests
        id: run_tests_2
        run: |
          echo "Running tests..."
          echo "::notice title=Test Passed::[PASS] Test ran successfully"
          # Simulate successful test
        continue-on-error: true

      - name: Log Test Failure
        if: steps.run_tests_2.outcome == 'failure'
        run: |
          echo "- 'Step 2 - Run tests' failed." >> $GITHUB_STEP_SUMMARY

      - name: Step 3 - Run tests
        id: run_tests_3
        run: |
          echo "Running tests..."
          gosho3  # Simulate failure
        continue-on-error: true

      - name: Log Test Failure
        if: steps.run_tests_3.outcome == 'failure'
        run: |
          echo "- 'Step 3 - Run tests' failed." >> $GITHUB_STEP_SUMMARY

      - name: Final Summary
        if: always()
        run: |
          echo "Final steps completed. Check the above errors for details."