on: [workflow_dispatch, push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    outputs:
      error_message: ${{ steps.check_step.outputs.error_message }}
    steps:
      - name: Run a task that might fail
        id: check_step
        run: |
          if ! some_command; then
            echo "error_message=Task failed due to X reason" >> $GITHUB_ENV
            exit 1
          fi
        continue-on-error: true

      - name: Init summary
        run: |
          echo "### Workflow Summary" >> $GITHUB_STEP_SUMMARY
          echo "Errors detected in the following steps:" >> $GITHUB_STEP_SUMMARY

      - name: Dummy fail test run
        run: |
          echo "Running test"
          exit 1
        

      - name: Test 1 Summary
        if: failure()
        run: |
          echo "- Test 1 Failed" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
          

      - name: Dummy pass test run
        run: |
          echo "Running test pass"
        

      - name: Test 2 summary
        if: failure()
        run: |
          echo "- Test 2 Failed" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

